# web server
openresty:
  build: ./openresty
  ports:
    - "80:80"
    - "443:443"
  # networks:
  #   - frontend
  volumes:
  #   # app
  - /home/wwwroot:/home/wwwroot
  #   # nginx configs
  - ./openresty/conf/:/etc/local/opresty/nginx/
  #   - ./openresty/conf.d/:/etc/loacl/openresty/nginx/conf.d/:ro
    # certificates
    # - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
    # - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
  # links:
  #   - php
  # depends_on:
  #           - php

# php-fpm
php:
  build: ./php
  ports:
    - "9000:9000"
  # networks:
  #   - frontend
  #   - backend
  environment:
            MYSQL_PASSWORD: ibenchu123
  # depends_on:
  #   - mysql
  #   - postgres
  # volumes:
  #   - ./app/src:/usr/share/nginx/html
  #   # Your php.ini
  #   - /home/config/php.ini:/usr/local/etc/php/php.ini:ro
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
    # links:
    #   - "mariadb"
    #   # - "redis"

# database
mariadb:
  image: mariadb:latest
  ports:
    # Allow client to access 3306
    - "3306:3306"
  volumes:
    # NOTE: your data will be stored in ./mysql
    - /home/data/mariadb:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=ibenchu123
  command: ['mysqld', '--character-set-server=utf8']
  # networks:
  #   - backend
pgsql:
  image: postgres:alpine
  ports:
    - "5432:5432"
  volumes:
       - /home/data/pgsql:/var/lib/postgresql/data:z
  environment:
       - POSTGRES_PASSWORD=ibenchu123

redis:
  image: redis:alpine
  command: redis-server --requirepass redis
  container_name: redis
  ports: 
    - "6379:6379"


